### ISSUE TITLE
Intermittent harvest failures

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#77]
Investigate:
	Request URL: https://ora4-qa-symp.bodleian.ox.ac.uk/sword/collections/default/works/uuid_7dbdb6a9-d8bf-42bc-bf66-db346e75dc5e
	
Investigate:
	Request URL: https://ora4-qa-symp.bodleian.ox.ac.uk/sword/collections/default/works/uuid_5978fd38-d2b5-4b9f-a282-fa22f61af64a
	
From Symplectic Logs area

Some harvests are failing and then succeeding. I don't know what the corresponding error is!

```
2019-06-26 11:07:01 [Hyrax synchroniser]: New work found. Waking up...
2019-06-26 11:07:01 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:07:02 [Hyrax synchroniser]: Hyrax reported that it experienced an unexpected internal error. If this problem persists, please contact the data service helpdesk for Hyrax.
2019-06-26 11:07:02 [Hyrax synchroniser]: Fetch batch errored. Retry postponed until after 26/06/2019 11:12:02.
2019-06-26 11:07:02 [Hyrax synchroniser]: Since the Hyrax synchroniser was last restarted, 0 work items have been automatically enqueued, 2 reactivated, 55 successfully processed, 0 discarded and 3 postponed. If no logging has appeared since the last such message, the ongoing work has resulted in no data changes.
2019-06-26 11:07:02 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:07:04 [Hyrax synchroniser]: Hyrax reported that it experienced an unexpected internal error. If this problem persists, please contact the data service helpdesk for Hyrax.
2019-06-26 11:07:04 [Hyrax synchroniser]: Fetch batch errored. Retry postponed until after 26/06/2019 11:12:04.
2019-06-26 11:07:04 [Hyrax synchroniser]: There is currently no more work to do.
...
2019-06-26 11:25:59 [Hyrax synchroniser]: A total of 1 Hyrax publications have been imported, but caused no changes, during this fetch/harvest batch.
2019-06-26 11:25:59 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:26:02 [Hyrax synchroniser]: Publication record 2909578 (Hyrax uuid_43ceaa00-0bc0-4402-b917-ec84d8ef4499): Not updated (no changes).
2019-06-26 11:26:02 [Hyrax synchroniser]: A total of 1 Hyrax publications have been imported, but caused no changes, during this fetch/harvest batch.
2019-06-26 11:26:02 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:26:07 [Hyrax synchroniser]: Publication record 2909580 (Hyrax uuid_c1788c6a-5951-4cd6-ac4c-9a7fbe7abd92): Not updated (no changes).
2019-06-26 11:26:07 [Hyrax synchroniser]: A total of 1 Hyrax publications have been imported, but caused no changes, during this fetch/harvest batch.
2019-06-26 11:26:07 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:26:08 [Hyrax synchroniser]: Publication record 2909592 (Hyrax 8c97kq405): Not updated (no changes).
2019-06-26 11:26:08 [Hyrax synchroniser]: A total of 1 Hyrax publications have been imported, but caused no changes, during this fetch/harvest batch.
2019-06-26 11:26:08 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:26:11 [Hyrax synchroniser]: Publication record 2909587 (Hyrax g445cd121): Not updated (no changes).
2019-06-26 11:26:11 [Hyrax synchroniser]: A total of 1 Hyrax publications have been imported, but caused no changes, during this fetch/harvest batch.
2019-06-26 11:26:11 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:26:15 [Hyrax synchroniser]: Publication record 2909589 (Hyrax n296wz12m): Not updated (no changes).
2019-06-26 11:26:15 [Hyrax synchroniser]: A total of 1 Hyrax publications have been imported, but caused no changes, during this fetch/harvest batch.
2019-06-26 11:26:15 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:26:18 [Hyrax synchroniser]: Publication record 2909591 (Hyrax 76537133j): Updated within Publication 1002262.
2019-06-26 11:26:18 [Hyrax synchroniser]: A total of 1 Hyrax publications have been updated during this fetch/harvest batch.
2019-06-26 11:26:18 [Hyrax synchroniser]: There is currently no more work to do.
2019-06-26 11:27:18 [Hyrax synchroniser]: 2 postponed Fetch work items reactivated.
2019-06-26 11:27:18 [Hyrax synchroniser]: New work found. Waking up...
2019-06-26 11:27:18 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:27:19 [Hyrax synchroniser]: Hyrax reported that it experienced an unexpected internal error. If this problem persists, please contact the data service helpdesk for Hyrax.
2019-06-26 11:27:19 [Hyrax synchroniser]: Fetch batch errored. Retry postponed until after 26/06/2019 12:12:19.
2019-06-26 11:27:19 [Hyrax synchroniser]: Since the Hyrax synchroniser was last restarted, 0 work items have been automatically enqueued, 6 reactivated, 165 successfully processed, 0 discarded and 7 postponed. If no logging has appeared since the last such message, the ongoing work has resulted in no data changes.
2019-06-26 11:27:19 [Hyrax synchroniser]: Processing priority 30 fetch for a batch of 1 records...
2019-06-26 11:27:21 [Hyrax synchroniser]: Hyrax reported that it experienced an unexpected internal error. If this problem persists, please contact the data service helpdesk for Hyrax.
2019-06-26 11:27:21 [Hyrax synchroniser]: Fetch batch errored. Retry postponed until after 26/06/2019 12:12:21.
2019-06-26 11:27:21 [Hyrax synchroniser]: There is currently no more work to do.
```

```
Potential Hyrax errors;

```
NoMethodError (undefined method `contributors' for nil:NilClass):
F, [2019-06-26T11:27:22.519125 #27180] FATAL -- : [6b0d8256-981b-476a-b561-753d960db368]   
F, [2019-06-26T11:27:22.519186 #27180] FATAL -- : [6b0d8256-981b-476a-b561-753d960db368] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/crosswalk_to_mods.rb:327:in 
`add_name_person'
[6b0d8256-981b-476a-b561-753d960db368] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/crosswalk_to_mods.rb:234:in `add_name'
[6b0d8256-981b-476a-b561-753d960db368] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/crosswalk_to_mods.rb:27:in `to_mods'
```

```
NoMethodError (undefined method `[]' for nil:NilClass):
F, [2019-06-26T11:27:20.529319 #27180] FATAL -- : [2473d6f0-3d0f-4dc3-a2fa-e570244c6d1e]   
F, [2019-06-26T11:27:20.529405 #27180] FATAL -- : [2473d6f0-3d0f-4dc3-a2fa-e570244c6d1e] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/crosswalk_to_mods.rb:645:in 
`add_ri_host'
[2473d6f0-3d0f-4dc3-a2fa-e570244c6d1e] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/crosswalk_to_mods.rb:562:in `add_related_item'

```

```
# THIS LOOKS LIKE AN OUTBOUND CROSSWALK ERROR

NoMethodError (undefined method `each' for nil:NilClass):
F, [2019-06-26T11:36:33.670704 #27180] FATAL -- : [90f9fa24-792c-4c60-8c32-7e630d1e212c]   
F, [2019-06-26T11:36:33.670767 #27180] FATAL -- : [90f9fa24-792c-4c60-8c32-7e630d1e212c] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:852:
in `assign_contributor_hash'
[90f9fa24-792c-4c60-8c32-7e630d1e212c] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:358:in `assign_name_person'
[90f9fa24-792c-4c60-8c32-7e630d1e212c] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:259:in `block in assign_name'

```

**Comment by tomwrobel** [comment]
Both of these objects were malformed on migration. This is not a Symplectic or Sword issue. For the ORA team, see https://trello.com/c/s3iJsdP2/258-part-of-510-some-objects-incorrectly-set-to-private-on-migration-to-ora4-qa-symp

Closing
